name: GitHub_Actions
on:
  push:
    branches:
      - develop
  workflow_dispatch:
  repository_dispatch:
    types: GitHub_Actions(gas)
env:  # 環境変数から文字列(パスワードなど)を取得
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
  IMGUR: ${{ secrets.IMGUR }}
  LINE_NOTIFY: ${{ secrets.LINE_NOTIFY }}
  WEBHOOK: ${{ secrets.WEBHOOK }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RUN_NUMBER: ${{ github.run_number }}
  RUN_ID: ${{ github.run_id }}
  TZ: 'Asia/Tokyo'
concurrency:  # 同時にworkflowが実行されたらキャンセル
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Run python
        id: results
        run: |
          echo '::group::pip install --upgrade pip'
          python -m pip install --upgrade pip==23.0
          pip install get-chrome-driver==1.3.10
          pip install selenium==4.8.0
          pip install tweepy==4.12.1
          echo '::endgroup::'
          python -B main.py
      - name: GitHub Summary
        run: |
          echo -e '- #### 時刻: ${{ steps.results.outputs.TIME }}' >> $GITHUB_STEP_SUMMARY

